/**
 * Default Templates Configuration
 */

import type { Template } from "@/interfaces/template.interfaces";

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: "modern-1",
    name: "templateFullNames.modernProfessional",
    style: "modern",
    description: "templateDescriptions.modern",
    thumbnail: "/templates/modern-1-thumb.png",
    previewImage: "/templates/modern-1-preview.png",
    isPremium: false,
    defaultSettings: {
      colors: {
        primary: "#2563eb",
        secondary: "#64748b",
        accent: "#3b82f6",
        text: "#1e293b",
        background: "#ffffff",
        border: "#e2e8f0",
      },
      typography: {
        fontFamily: "Inter, sans-serif",
        headingFontFamily: "Inter, sans-serif",
        fontSize: {
          heading1: "2rem",
          heading2: "1.5rem",
          heading3: "1.25rem",
          body: "1rem",
          small: "0.875rem",
        },
      },
      layout: {
        columnCount: 2,
        spacing: "normal",
        margins: {
          top: 40,
          right: 40,
          bottom: 40,
          left: 40,
        },
        sectionSpacing: 24,
      },
    },
    defaultComponents: [
      "header",
      "contact",
      "summary",
      "experience",
      "education",
      "skills",
    ],
  },
  {
    id: "classic-1",
    name: "templateFullNames.classicElegance",
    style: "classic",
    description: "templateDescriptions.classic",
    thumbnail: "/templates/classic-1-thumb.png",
    previewImage: "/templates/classic-1-preview.png",
    isPremium: false,
    defaultSettings: {
      colors: {
        primary: "#1f2937",
        secondary: "#6b7280",
        accent: "#374151",
        text: "#111827",
        background: "#ffffff",
        border: "#d1d5db",
      },
      typography: {
        fontFamily: "Georgia, serif",
        headingFontFamily: "Georgia, serif",
        fontSize: {
          heading1: "2.25rem",
          heading2: "1.75rem",
          heading3: "1.375rem",
          body: "1rem",
          small: "0.875rem",
        },
      },
      layout: {
        columnCount: 1,
        spacing: "relaxed",
        margins: {
          top: 50,
          right: 50,
          bottom: 50,
          left: 50,
        },
        sectionSpacing: 32,
      },
    },
    defaultComponents: [
      "header",
      "contact",
      "summary",
      "experience",
      "education",
      "skills",
    ],
  },
  {
    id: "minimal-1",
    name: "templateFullNames.minimalClean",
    style: "minimal",
    description: "templateDescriptions.minimal",
    thumbnail: "/templates/minimal-1-thumb.png",
    previewImage: "/templates/minimal-1-preview.png",
    isPremium: false,
    defaultSettings: {
      colors: {
        primary: "#000000",
        secondary: "#737373",
        accent: "#404040",
        text: "#171717",
        background: "#ffffff",
        border: "#e5e5e5",
      },
      typography: {
        fontFamily: "Helvetica, Arial, sans-serif",
        headingFontFamily: "Helvetica, Arial, sans-serif",
        fontSize: {
          heading1: "2rem",
          heading2: "1.5rem",
          heading3: "1.125rem",
          body: "0.9375rem",
          small: "0.8125rem",
        },
      },
      layout: {
        columnCount: 1,
        spacing: "compact",
        margins: {
          top: 35,
          right: 35,
          bottom: 35,
          left: 35,
        },
        sectionSpacing: 20,
      },
    },
    defaultComponents: [
      "header",
      "contact",
      "summary",
      "experience",
      "skills",
      "projects",
    ],
  },
  {
    id: "creative-1",
    name: "templateFullNames.creativeBold",
    style: "creative",
    description: "templateDescriptions.creative",
    thumbnail: "/templates/creative-1-thumb.png",
    previewImage: "/templates/creative-1-preview.png",
    isPremium: true,
    defaultSettings: {
      colors: {
        primary: "#7c3aed",
        secondary: "#a78bfa",
        accent: "#8b5cf6",
        text: "#1f2937",
        background: "#ffffff",
        border: "#e9d5ff",
      },
      typography: {
        fontFamily: "Montserrat, sans-serif",
        headingFontFamily: "Montserrat, sans-serif",
        fontSize: {
          heading1: "2.5rem",
          heading2: "1.75rem",
          heading3: "1.375rem",
          body: "1rem",
          small: "0.875rem",
        },
      },
      layout: {
        columnCount: 2,
        spacing: "normal",
        margins: {
          top: 40,
          right: 40,
          bottom: 40,
          left: 40,
        },
        sectionSpacing: 28,
      },
    },
    defaultComponents: [
      "header",
      "contact",
      "summary",
      "projects",
      "experience",
      "skills",
      "education",
    ],
  },
  {
    id: "professional-1",
    name: "templateFullNames.professionalExecutive",
    style: "professional",
    description: "templateDescriptions.professional",
    thumbnail: "/templates/professional-1-thumb.png",
    previewImage: "/templates/professional-1-preview.png",
    isPremium: true,
    defaultSettings: {
      colors: {
        primary: "#0f172a",
        secondary: "#475569",
        accent: "#1e293b",
        text: "#0f172a",
        background: "#ffffff",
        border: "#cbd5e1",
      },
      typography: {
        fontFamily: "Crimson Text, serif",
        headingFontFamily: "Crimson Text, serif",
        fontSize: {
          heading1: "2.5rem",
          heading2: "1.875rem",
          heading3: "1.5rem",
          body: "1.0625rem",
          small: "0.9375rem",
        },
      },
      layout: {
        columnCount: 2,
        spacing: "relaxed",
        margins: {
          top: 45,
          right: 45,
          bottom: 45,
          left: 45,
        },
        sectionSpacing: 30,
      },
    },
    defaultComponents: [
      "header",
      "contact",
      "summary",
      "experience",
      "education",
      "certifications",
      "skills",
    ],
  },
];
